version: '3'
services:
  db:
    image: postgres
    container_name: gomap_db
    environment:
      - POSTGRES_USER=gomap_admin
      - POSTGRES_PASSWORD=gomap_admin
      - POSTGRES_DB=gomap_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: gomap_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_KEY: ${SSH_KEY}
    ports:
      - 8001:8001
    depends_on:
      - db
      